### ISSUE TITLE
Add auth callback URL and credential properties

### ISSUE THREAD

**Issue by jbonofre** [huaweicloud/osc#24]
To create resources in the orchestrator plugin, we need authentication information.
I propose to add ` authentication` list at ` OCL` level. It will like:

```
  "authentication": [
     {
         "id": "main_auth",
         "url": "https://identity.api.my.cloud:443/v3/auth/tokens",
         "properties": {
             "tenant": "${env:tenant}",
             "username": "${secret:username}",
             "password": "${secret:password}"
          }
  ]
```

Thoughts ?

**Comment by jbonofre** [comment]
@niuzhenguo @iskey thoughts ?

**Comment by iskey** [comment]
I think the authentication should be different per CSP. 
How about using an undefined "environment" block to give CSP plugin a chance to inject its parameters (including authentication)?

```
"environment": {
}
```
The CSP provider will explain this block.

**Comment by jbonofre** [comment]
Agree. We can use the properties at OCL higher level or add an environment section.

**Comment by iskey** [comment]
Agree.

**Comment by jbonofre** [comment]
Ok let me illustrate properties usage for authentication in openstack orchestrator plugin.

**Comment by jbonofre** [comment]
So, as it has to be managed directly by the plugin (leveraging system props / env variables), we can close this one.
