### ISSUE TITLE
Create orchestrator storage in HuaweiCloud plugin

### ISSUE THREAD

**Issue by jbonofre** [huaweicloud/osc#30]
Add OBS impl for orchestrator storage in HuaweiCloud plugin

OBS sdk: https://github.com/huaweicloud/huaweicloud-sdk-java-obs

**Comment by jbonofre** [comment]
@niuzhenguo @iskey I guess this one is fixed right ?

**Comment by niuzhenguo** [comment]
> @niuzhenguo @iskey I guess this one is fixed right ?

yes, this one can be closed.

**Comment by jbonofre** [comment]
@niuzhenguo thanks, now December sprint is clean :)
