### ISSUE TITLE
Add runtime properties for meta.

### ISSUE THREAD

**Issue by iskey** [huaweicloud/osc#43]
Add a `RuntimeBase` class as the basic of runtime meta.

**Comment by iskey** [comment]
@jbonofre @niuzhenguo, i want to add a `RuntimeBase` as the superclass of the runtime `ocl-meta`. 
Then, we can serialize/deserialize the middle-state/final-state of the OCL meta. thoughts?

**Comment by iskey** [comment]
Either should we use the Ocl object or a serial of new objects (runtime VM/VPC/SUBNET/STORAGE) to carry these runtime informations?

**Comment by iskey** [comment]
@niuzhenguo @jbonofre, I think we must decide this before we get the plugin going.

**Comment by jbonofre** [comment]
@iskey it sounds good to me. I think we can "reuse" the OCL objects for that, we will see if we need "inner" objects while implementing.

**Comment by iskey** [comment]
Thanks.
