### ISSUE TITLE
Export a new API for resource information

### ISSUE THREAD

**Issue by iskey** [huaweicloud/osc#82]
Export a new API for the status and properties of the managed infra.

**Comment by jbonofre** [comment]
By API, you mean in the `services/api`module ?

**Comment by iskey** [comment]
I thought so.
From my view, the '/start' should be an asynchronous API, for the builder may take a long time to build the resource, so we need another API to get the status and properties.
Does it make sense?

**Comment by jbonofre** [comment]
Ok, it makes sense. The reason when I'm asking is because it impacts all plugins. So I will have to update openstack and k8s plugins. Thanks !

**Comment by iskey** [comment]
@jbonofre ，Hi
I want to add the `services/state/{managedServices}` API to expose the state of the Ocl resources.
By the way, I propose adding an `OclResource` object to make a flat view of all the Ocl resources. 
Just like this:
```json
{
  "state" : "active",
  "resources" : [ {
    "state" : "active",
    "id" : "8f081807-5bba-487a-8955-91f915af31c2",
    "type" : "image",
    "name" : "kafka_image",
    "properties" : { }
  }, {
    "state" : "active",
    "id" : "634c1a24-05f7-4c69-a776-f1a0c6c97b81",
    "type" : "compute",
    "name" : "osc-kafka-vm",
    "properties" : {
      "ipv6" : "",
      "ip" : "10.10.1.142",
      "id" : "634c1a24-05f7-4c69-a776-f1a0c6c97b81"
    }
  }, {
    "state" : "active",
    "id" : "bef5db0c-7a64-4c1b-8a24-5f5c6d16dae2",
    "type" : "storage",
    "name" : "osc-res-storage",
    "properties" : {
      "size" : "20",
      "type" : "SAS"
    }
  }, {
    "state" : "active",
    "id" : "b826d542-85c1-4b68-9fba-4216d8acf9d9",
    "type" : "security",
    "name" : "osc-res-sg",
    "properties" : { }
  },
  {
    "state" : "active",
    "id" : "30dede94-be03-48da-9595-80b2c3c24760",
    "type" : "vpc",
    "name" : "osc-res-vpc",
    "properties" : {
      "cidr" : "10.10.0.0/16",
      "id" : "30dede94-be03-48da-9595-80b2c3c24760",
      "region" : "cn-north-4"
    }
  }, 
  {
    "state" : "active",
    "id" : "1a3a85b3-e1a9-42e5-bd4e-8be49a518d80",
    "type" : "subnet",
    "name" : "osc-res-subnet",
    "properties" : {
      "vpc" : "30dede94-be03-48da-9595-80b2c3c24760",
      "cidr" : "10.10.1.0/24"
    }
  } ]
}
``` 

Any suggestion?

**Comment by jbonofre** [comment]
I guess we need two things:
1. Add a new `OclResourceService` in a dedicated module (or maybe it can be part of the orchestrator, not sure though)
2. Add new REST API in `modules/api` exposing `state` API and leverage the `OclResourceService`.
WDYT ?

**Comment by iskey** [comment]
ok, I agree with you.
I pushed a PR (#91 ) for this yet, could please leave me some suggestions?
